name: travel_app
description: "A new Flutter project."

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  flutter_svg: ^2.0.17
  bloc: ^9.0.0
  equatable: ^2.0.7
  flutter_bloc: ^9.0.0
  intl: ^0.20.2
  marquee: ^2.3.0
  form_field_validator: ^1.1.0
  cached_network_image: ^3.4.1
  flutter_map: ^8.0.0
  latlong2: ^0.9.1
  http: ^1.3.0
  flutter_email_sender: ^7.0.0
  flutter_dotenv: ^5.1.0
  mailer: ^6.0.1
  url_launcher_android: ^6.3.15
  url_launcher_platform_interface: ^2.3.2
  polyline_codec: ^0.1.6



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/svgIcons/
    - .env
