// Client
const START_LOCATION_RESERVE_DELIVERY_SCREEN =
    "START_LOCATION_RESERVE_DELIVERY_SCREEN";
const END_LOCATION_RESERVE_DELIVERY_SCREEN =
    "END_LOCATION_RESERVE_DELIVERY_SCREEN";

const START_LOCATION_RESERVE_RIDE_SCREEN =
    "START_LOCATION_RESERVE_DELIVERY_SCREEN";
const END_LOCATION_RESERVE_RIDE_SCREEN = "END_LOCATION_RESERVE_DELIVERY_SCREEN";
const RESERVE_RIDE_SCREEN = "RESERVE_RIDE_SCREEN";

// Admin
const START_LOCATION_ADD_DELIVERY_SCREEN = "START_LOCATION_ADD_DELIVERY_SCREEN";
const END_LOCATION_ADD_DELIVERY_SCREEN = "END_LOCATION_ADD_DELIVERY_SCREEN";

const START_LOCATION_ADD_RIDE_SCREEN = "START_LOCATION_ADD_RIDE_SCREEN";

const START_LOCATION_DELIVERY_DETAILS_SCREEN =
    "START_LOCATION_DELIVERY_DETAILS_SCREEN";
const END_LOCATION_DELIVERY_DETAILS_SCREEN =
    "END_LOCATION_DELIVERY_DETAILS_SCREEN";
